[package]
name = "firmware"
version = "0.1.0"
authors = ["Oliver Trevor <featherfeet5436@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
